blank_issues_enabled: true
contact_links:
  - name: Questions or need suggestions?
    url: https://github.com/YadavAkhileshh/Alien-Invasion-Defense/discussions/new?category=q-a
    about: You can create a Q&A discussion and ask for clarifications 
